[theme]
primaryColor = "#2563EB"
backgroundColor = "#0A0E1A"
secondaryBackgroundColor = "#151922"
textColor = "#FFFFFF"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
